services:
  fury:
    build:
      args:
        ENVIRONMENT: dev
        PORT: 5000
        USER: fury
        GROUP: darksiders
      context: .
      dockerfile: Dockerfile
    container_name: fury
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - furynet
      - busnet
      - cachenet
      - dbnet
      - blobnet
    secrets:
      - source: db_ca_crt
        target: ca.crt
      - source: db_client_root_key
        target: client.root.key
        mode: 0600
      - source: db_client_root_crt
        target: client.root.crt

networks:
  furynet:
    driver: bridge